### ISSUE TITLE
Error thrown in sample code

### ISSUE THREAD

**Issue by charleslcso** [feathersjs-ecosystem/feathers-mongodb#154]
### Steps to reproduce
Use the sample code in github, it first of all throws an error saying the new parser should be used.

bash-3.2$ node app.js
(node:1791) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
Feathers server listening on port 3030
Error: Slash in host identifier
    at parseConnectionString (/Applications/nodejs-10.16.3-0/apps/node_modules/mongodb/lib/url_parser.js:221:15)
    at parseHandler (/Applications/nodejs-10.16.3-0/apps/node_modules/mongodb/lib/url_parser.js:130:14)
    at module.exports (/Applications/nodejs-10.16.3-0/apps/node_modules/mongodb/lib/url_parser.js:26:12)
    at deprecated (internal/util.js:66:15)
    at connect (/Applications/nodejs-10.16.3-0/apps/node_modules/mongodb/lib/operations/connect.js:266:3)
    at ConnectOperation.execute (/Applications/nodejs-10.16.3-0/apps/node_modules/mongodb/lib/operations/connect.js:191:5)
    at /Applications/nodejs-10.16.3-0/apps/node_modules/mongodb/lib/operations/execute_operation.js:109:26
    at new Promise (<anonymous>)
    at executeOperation (/Applications/nodejs-10.16.3-0/apps/node_modules/mongodb/lib/operations/execute_operation.js:102:10)
    at MongoClient.connect (/Applications/nodejs-10.16.3-0/apps/node_modules/mongodb/lib/mongo_client.js:216:10)

Then revised the sample code to use:
const MongoClient = require('mongodb').MongoClient({ useNewUrlParser: true });

then it throws another error, saying the method "connect" only accepts a callback.

bash-3.2$ node app.js
/Applications/nodejs-10.16.3-0/apps/node_modules/mongodb/lib/mongo_client.js:211
    throw new TypeError('`connect` only accepts a callback');
    ^

TypeError: `connect` only accepts a callback
    at MongoClient.connect (/Applications/nodejs-10.16.3-0/apps/node_modules/mongodb/lib/mongo_client.js:211:11)
    at Object.<anonymous> (/Applications/nodejs-10.16.3-0/apps/app.js:31:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Module versions** (especially the part that's not working):

**NodeJS version**:
node -v
v10.16.3

**Operating System**:
OS X 10.13.6

**Browser Version**:
Command line

**Comment by Pogix3m** [comment]
@charleslcso 
I think you should pass first the **url** for the mongodb

```
const MongoClient = require('mongodb').MongoClient('mongodb://localhost:27017/feathers', { useNewUrlParser: true });
```
